[package]
name = "telegram-drive-headless"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
actix-multipart = "0.7"
actix-web = "4"
async-stream = "0.3"
constant_time_eq = "0.3"
env_logger = "0.11"
futures = "0.3"
grammers-client = { git = "https://github.com/Lonami/grammers", rev = "d07f96f" }
grammers-mtsender = { git = "https://github.com/Lonami/grammers", rev = "d07f96f" }
grammers-session = { git = "https://github.com/Lonami/grammers", rev = "d07f96f" }
grammers-tl-types = { git = "https://github.com/Lonami/grammers", rev = "d07f96f" }
log = "0.4"
rpassword = "7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
